=== invopop/gobl.ruby/data/schemas/tax/region.json
{
  "$schema": "http://json-schema.org/draft/2020-12/schema",
  "$id": "https://gobl.org/draft-0/tax/region",
  "$ref": "#/$defs/Region",
  "$defs": {
    "Category": {
      "properties": {
        "code": {
          "type": "string",
          "title": "Code"
        },
        "name": {
          "$ref": "https://gobl.org/draft-0/i18n/string",
          "title": "Name"
        },
        "desc": {
          "$ref": "https://gobl.org/draft-0/i18n/string",
          "title": "Description"
        },
        "retained": {
          "type": "boolean",
          "title": "Retained",
          "description": "Retained when true implies that the tax amount will be retained\nby the buyer on behalf of the supplier, and thus subtracted from\nthe invoice taxable base total. Typically used for taxes related to\nincome."
        },
        "rates": {
          "items": {
            "$ref": "#/$defs/Rate"
          },
          "type": "array",
          "title": "Rates",
          "description": "Specific tax definitions inside this category."
        }
      },
      "type": "object",
      "required": [
        "code",
        "name",
        "rates"
      ],
      "description": "Category contains the definition of a general type of tax inside a region."
    },
    "Note": {
      "properties": {
        "key": {
          "type": "string",
          "title": "Key",
          "description": "Key specifying subject of the text"
        },
        "code": {
          "type": "string",
          "title": "Code",
          "description": "Code used for additional data that may be required to identify the note."
        },
        "src": {
          "type": "string",
          "title": "Source",
          "description": "Source of this note, especially useful when auto-generated."
        },
        "text": {
          "type": "string",
          "title": "Text",
          "description": "The contents of the note"
        }
      },
      "type": "object",
      "required": [
        "text"
      ],
      "description": "Note represents a free text of additional information that may be added to a document."
    },
    "Rate": {
      "properties": {
        "key": {
          "type": "string",
          "title": "Key",
          "description": "Key identifies this rate within the system"
        },
        "name": {
          "$ref": "https://gobl.org/draft-0/i18n/string",
          "title": "Name"
        },
        "desc": {
          "$ref": "https://gobl.org/draft-0/i18n/string",
          "title": "Description"
        },
        "values": {
          "items": {
            "$ref": "#/$defs/RateValue"
          },
          "type": "array",
          "title": "Values",
          "description": "Values contains a list of Value objects that contain the\ncurrent and historical percentage values for the rate;\norder is important, newer values should come before\nolder values."
        }
      },
      "type": "object",
      "required": [
        "key",
        "name",
        "values"
      ],
      "description": "Rate defines a single rate inside a category"
    },
    "RateValue": {
      "properties": {
        "since": {
          "$ref": "https://gobl.org/draft-0/cal/date",
          "title": "Since",
          "description": "Date from which this value should be applied."
        },
        "percent": {
          "$ref": "https://gobl.org/draft-0/num/percentage",
          "title": "Percent",
          "description": "Rate that should be applied"
        },
        "disabled": {
          "type": "boolean",
          "title": "Disabled",
          "description": "When true, this value should no longer be used."
        }
      },
      "type": "object",
      "required": [
        "percent"
      ],
      "description": "RateValue contains a percentage rate or fixed amount for a given date range."
    },
    "Region": {
      "properties": {
        "name": {
          "$ref": "https://gobl.org/draft-0/i18n/string",
          "title": "Name",
          "description": "Name of the region"
        },
        "country": {
          "type": "string",
          "title": "Code",
          "description": "Country code for the region"
        },
        "locality": {
          "type": "string",
          "title": "Locality",
          "description": "Locality, city, region, or similar code inside the country, if needed."
        },
        "currency": {
          "type": "string",
          "title": "Currency",
          "description": "Currency used by the region for tax purposes."
        },
        "schemes": {
          "$ref": "#/$defs/Schemes",
          "title": "Schemes",
          "description": "Set of specific scheme definitions inside the region."
        },
        "categories": {
          "items": {
            "$ref": "#/$defs/Category"
          },
          "type": "array",
          "title": "Categories",
          "description": "List of tax categories."
        }
      },
      "type": "object",
      "required": [
        "name",
        "country",
        "currency",
        "categories"
      ],
      "description": "Region defines the holding structure for a regions categories and subsequent Rates and Values."
    },
    "Scheme": {
      "properties": {
        "key": {
          "type": "string",
          "title": "Key",
          "description": "Key used to identify this scheme"
        },
        "name": {
          "$ref": "https://gobl.org/draft-0/i18n/string",
          "title": "Name",
          "description": "Name of this scheme."
        },
        "description": {
          "$ref": "https://gobl.org/draft-0/i18n/string",
          "title": "Description",
          "description": "Human details describing what this scheme is used for."
        },
        "categories": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "title": "Category Codes",
          "description": "List of tax category codes that can be used when this scheme is\napplied."
        },
        "note": {
          "$ref": "#/$defs/Note",
          "title": "Note",
          "description": "Notes defines messages that should be added to a document\nwhen this scheme is used."
        }
      },
      "type": "object",
      "required": [
        "key",
        "name"
      ],
      "description": "Scheme contains the definition of a scheme that belongs to a region and can be used to simplify validation processes for document contents."
    },
    "Schemes": {
      "items": {
        "$ref": "#/$defs/Scheme"
      },
      "type": "array",
      "description": "Schemes defines an array of scheme objects with helper functions."
    }
  },
  "$comment": "Generated with GOBL v0.22.0"
}

=== invopop/gobl.ruby/data/tax/ES.json
{
  "$schema": "https://gobl.org/draft-0/tax/region",
  "name": {
    "en": "Spain",
    "es": "España"
  },
  "country": "ES",
  "currency": "EUR",
  "schemes": [
    {
      "key": "reverse-charge",
      "name": {
        "en": "Reverse Charge",
        "es": "Inversión del sujeto pasivo"
      },
      "categories": [
        "VAT"
      ],
      "note": {
        "key": "legal",
        "src": "reverse-charge",
        "text": "Reverse Charge / Inversión del sujeto pasivo."
      }
    },
    {
      "key": "customer-rates",
      "name": {
        "en": "Customer Country Rates",
        "es": "Tasas del País del Cliente"
      },
      "description": {
        "en": "Use the customers country to determine tax rates."
      }
    },
    {
      "key": "simplified",
      "name": {
        "en": "Simplified tax scheme",
        "es": "Contribuyente en régimen simplificado"
      },
      "note": {
        "key": "legal",
        "src": "simplified",
        "text": "Factura expedida por contibuyente en régimen simplificado."
      }
    },
    {
      "key": "customer-issued",
      "name": {
        "en": "Customer issued invoice",
        "es": "Facturación por el destinatario"
      },
      "note": {
        "key": "legal",
        "src": "customer-issued",
        "text": "Facturación por el destinatario."
      }
    },
    {
      "key": "travel-agency",
      "name": {
        "en": "Special scheme for travel agencies",
        "es": "Régimen especial de las agencias de viajes"
      },
      "note": {
        "key": "legal",
        "src": "travel-agency",
        "text": "Régimen especial de las agencias de viajes."
      }
    },
    {
      "key": "second-hand-goods",
      "name": {
        "en": "Special scheme for second-hand goods",
        "es": "Régimen especial de los bienes usados"
      },
      "note": {
        "key": "legal",
        "src": "second-hand-goods",
        "text": "Régimen especial de los bienes usados."
      }
    },
    {
      "key": "art",
      "name": {
        "en": "Special scheme of works of art",
        "es": "Régimen especial de los objetos de arte"
      },
      "note": {
        "key": "legal",
        "src": "art",
        "text": "Régimen especial de los objetos de arte."
      }
    },
    {
      "key": "antiques",
      "name": {
        "en": "Special scheme of antiques and collectables",
        "es": "Régimen especial de las antigüedades y objetos de colección"
      },
      "note": {
        "key": "legal",
        "src": "antiques",
        "text": "Régimen especial de las antigüedades y objetos de colección."
      }
    },
    {
      "key": "cash-basis",
      "name": {
        "en": "Special scheme on cash basis",
        "es": "Régimen especial del criterio de caja"
      },
      "note": {
        "key": "legal",
        "src": "cash-basis",
        "text": "Régimen especial del criterio de caja."
      }
    }
  ],
  "categories": [
    {
      "code": "VAT",
      "name": {
        "en": "VAT",
        "es": "IVA"
      },
      "desc": {
        "en": "Value Added Tax",
        "es": "Impuesto sobre el Valor Añadido"
      },
      "rates": [
        {
          "key": "zero",
          "name": {
            "en": "Zero Rate",
            "es": "Tipo Zero"
          },
          "values": [
            {
              "percent": "0.0%"
            }
          ]
        },
        {
          "key": "standard",
          "name": {
            "en": "Standard Rate",
            "es": "Tipo General"
          },
          "values": [
            {
              "since": "2012-09-01",
              "percent": "21.0%"
            },
            {
              "since": "2010-07-01",
              "percent": "18.0%"
            },
            {
              "since": "1995-01-01",
              "percent": "16.0%"
            },
            {
              "since": "1993-01-01",
              "percent": "15.0%"
            }
          ]
        },
        {
          "key": "reduced",
          "name": {
            "en": "Reduced Rate",
            "es": "Tipo Reducido"
          },
          "values": [
            {
              "since": "2012-09-01",
              "percent": "10.0%"
            },
            {
              "since": "2010-07-01",
              "percent": "8.0%"
            },
            {
              "since": "1995-01-01",
              "percent": "7.0%"
            },
            {
              "since": "1993-01-01",
              "percent": "6.0%"
            }
          ]
        },
        {
          "key": "super-reduced",
          "name": {
            "en": "Super-Reduced Rate",
            "es": "Tipo Superreducido"
          },
          "values": [
            {
              "since": "1995-01-01",
              "percent": "4.0%"
            },
            {
              "since": "1993-01-01",
              "percent": "3.0%"
            }
          ]
        }
      ]
    },
    {
      "code": "VATEQS",
      "name": {
        "en": "VAT Equalization Surcharge",
        "es": "IVA Recargo de Equivalencia"
      },
      "rates": [
        {
          "key": "standard",
          "name": {
            "en": "Standard Rate",
            "es": "Tipo General"
          },
          "values": [
            {
              "since": "2012-09-01",
              "percent": "5.2%"
            },
            {
              "since": "1993-01-01",
              "percent": "4.0%"
            }
          ]
        },
        {
          "key": "reduced",
          "name": {
            "en": "Reduced Rate",
            "es": "Tipo Reducido"
          },
          "values": [
            {
              "since": "2012-09-01",
              "percent": "1.4%"
            },
            {
              "since": "1993-01-01",
              "percent": "1.0%"
            }
          ]
        },
        {
          "key": "super-reduced",
          "name": {
            "en": "Super-Reduced Rate",
            "es": "Tipo Superreducido"
          },
          "values": [
            {
              "since": "1993-01-01",
              "percent": "0.5%"
            }
          ]
        },
        {
          "key": "tobacco",
          "name": {
            "en": "Tobacco Rate",
            "es": "Tipo Tobaco"
          },
          "values": [
            {
              "since": "2007-01-01",
              "percent": "1.75%"
            }
          ]
        }
      ]
    },
    {
      "code": "IRPF",
      "name": {
        "en": "IRPF",
        "es": "IRPF"
      },
      "desc": {
        "en": "Personal income tax.",
        "es": "Impuesto sobre la renta de las personas físicas."
      },
      "retained": true,
      "rates": [
        {
          "key": "pro",
          "name": {
            "en": "Professional Rate",
            "es": "Professionales"
          },
          "values": [
            {
              "since": "2015-07-12",
              "percent": "15.0%"
            },
            {
              "since": "2015-01-01",
              "percent": "19.0%"
            },
            {
              "since": "2012-09-01",
              "percent": "21.0%"
            },
            {
              "since": "2007-01-01",
              "percent": "15.0%"
            }
          ]
        },
        {
          "key": "pro-start",
          "name": {
            "en": "Professional Starting Rate",
            "es": "Professionales Inicio"
          },
          "values": [
            {
              "since": "2007-01-01",
              "percent": "7.0%"
            }
          ]
        },
        {
          "key": "capital",
          "name": {
            "en": "Rental or Interest Capital",
            "es": "Alquileres o Intereses de Capital"
          },
          "values": [
            {
              "since": "2007-01-01",
              "percent": "19.0%"
            }
          ]
        },
        {
          "key": "modules",
          "name": {
            "en": "Modules Rate",
            "es": "Tipo Modulos"
          },
          "values": [
            {
              "since": "2007-01-01",
              "percent": "1.0%"
            }
          ]
        }
      ]
    }
  ]
}

=== invopop/gobl.ruby/data/regimes/nl.json
{
  "$schema": "https://gobl.org/draft-0/tax/regime",
  "name": {
    "en": "The Netherlands",
    "nl": "Nederland"
  },
  "country": "NL",
  "currency": "EUR",
  "categories": [
    {
      "code": "VAT",
      "name": {
        "en": "VAT",
        "nl": "BTW"
      },
      "desc": {
        "en": "Value Added Tax",
        "nl": "Belasting Toegevoegde Waarde"
      },
      "rates": [
        {
          "key": "zero",
          "name": {
            "en": "Zero Rate",
            "nl": "0%-tarief"
          },
          "values": [
            {
              "percent": "0.0%"
            }
          ]
        },
        {
          "key": "standard",
          "name": {
            "en": "Standard Rate",
            "nl": "Standaardtarief"
          },
          "values": [
            {
              "percent": "21.0%"
            }
          ]
        },
        {
          "key": "reduced",
          "name": {
            "en": "Reduced Rate",
            "nl": "Gereduceerd Tarief"
          },
          "values": [
            {
              "percent": "9.0%"
            }
          ]
        }
      ]
    }
  ]
}
